---
sidebar: false
toc: false
---

# Deutsch for English-speakers

## Description

The goal of these materials are to provide a basic understanding of the German language for English-speakers where the explanations for the concepts and sentence structure will be provided in English. I should be clear from the start that my grasp of the German language is incomplete, but I am trying to write up lessons as my knowledge grows.

A major concept for language learning is vocabulary acquisition. In these materials, we are going to attempt to limit the vocabulary and rather focus on how the language itself works. At some points vocabulary will be necessary to progress, but I will be making attempts to minimize this as much as possible.

## Learning Objectives

In these lessons, the learner will:

- Describe grammar concepts from German
- Assemble German sentences


## Lessons
* [Table of Contents](lessons/TOC.qmd)

## Licenses

Unless otherwise noted, the original teaching materials in this repository (text, exercises, and code) are distributed under the  [Creative Commons Attribution–ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/deed.en).

### Pronunciation audio

Pronunciation audio files are sourced from [Wiktionary](https://en.wiktionary.org/). Those files retain their original licenses (for example, various Creative Commons licenses or public-domain dedications) as specified on their Wiktionary file pages. If you wish to reuse those pronunciation files, please check the license information for each file on Wiktionary and follow the corresponding terms of use and attribution.
