---
title: "Present Tense Verb Conjugation - Exceptions"
author: "Will Gammerdinger"
date: Saturday, October 25th, 2025
---

Approximate time: 45 minutes

# Learning Objectives

In this lesson, the learner will:

- Categorize exceptions to the "normal" way of conjugating verbs in the present tense

# Sein

*Sein* <span class="pron" data-src="../audio/verben/sein/sein.ogg">🔊</span> (to be) is probably the most difficult verb to conjugate in the present tense because it doesn't follow any particular rules and you need to just memorize its conjugation. The good news is that you will you use it so frequently that it will become second-nature rather quickly. Below is the conjugation table for *sein*:

<div style="text-align: center;">
**sein** <span class="pron" data-src="../audio/verben/sein/sein.ogg">🔊</span> (to be) 
</div>

|||
|:---:|:---:|
| ich **bin** <span class="pron" data-src="../audio/verben/sein/bin.ogg">🔊</span> | wir **sind** <span class="pron" data-src="../audio/verben/sein/sind.ogg">🔊</span> |
| du **bist** <span class="pron" data-src="../audio/verben/sein/bist.ogg">🔊</span> | ihr **seid** <span class="pron" data-src="../audio/verben/sein/seid.ogg">🔊</span> |
| er **ist** <span class="pron" data-src="../audio/verben/sein/ist.ogg">🔊</span> <br>sie **ist**<br>es **ist** | Sie **sind** <span class="pron" data-src="../audio/verben/sein/sind.ogg">🔊</span><br>sie **sind** |

# Infinitive stem endings that cause issues

There are some sets of verbs where the verb stem (the verb after removing *-en*) ends in letters that require special care. We will talk about these in the sections below.

## Infinitive stems ending in *-s*, *-ß*, *-x* or *-z*

Infinitive verbs whose stem ends in *-s*, *-ß*, *-x* or *-z*  only add a *-t* in the second-person singular. The rationale for this is that these infinitive stems already have either an *-s* sound at the end of the stem or a sound that is somewhat similar to *-s*. As a result, adding an *-st* ending wouldn't be heard any different than *-t*. Some common words that fall into this category are:

| *-s* |*-ß* |*-x* |*-z* |
|:---:|:---:|:---:|:---:|
| **reisen** <span class="pron" data-src="../audio/verben/reisen/reisen.ogg">🔊</span> (to travel) | **heißen** <span class="pron" data-src="../audio/verben/heißen/heißen.ogg">🔊</span> (to be named) | **faxen** <span class="pron" data-src="../audio/verben/faxen/faxen.ogg">🔊</span> (to fax) | **tanzen** <span class="pron" data-src="../audio/verben/tanzen/tanzen.ogg">🔊</span> (to dance) |
|| **schließen** <span class="pron" data-src="../audio/verben/schließen/schließen.ogg">🔊</span> (to close) | **mixen** <span class="pron" data-src="../audio/verben/mixen/mixen.ogg">🔊</span> (to mix) | **sitzen** <span class="pron" data-src="../audio/verben/sitzen/sitzen.ogg">🔊</span>  (to sit)|
|| **grüßen** <span class="pron" data-src="../audio/verben/grüßen/grüßen.ogg">🔊</span> (to greet) || **besitzen** <span class="pron" data-src="../audio/verben/besitzen/besitzen.ogg">🔊</span> (to own) |

:::{.callout-note}
# Relation between *-ß* and *-ss*
This is probably a good place to point out that *-s* and *-ß* related. The *-ß* is sometimes replaced with *-ss*. As such, rules that apply to *-s* will also apply to *-ß*.
:::

Let's see an example of one of these conjugations:

<div style="text-align: center;">
**heißen** <span class="pron" data-src="../audio/verben/heißen/heißen.ogg">🔊</span> (to be named)
</div>

|||
|:---:|:---:|
| ich heiß**e** <span class="pron" data-src="../audio/verben/heißen/heiße.ogg">🔊</span> | wir heiß**en** <span class="pron" data-src="../audio/verben/heißen/heißen.ogg">🔊</span> |
| du heiß**t** <span class="pron" data-src="../audio/verben/heißen/heißt.ogg">🔊</span> | ihr heiß**t** <span class="pron" data-src="../audio/verben/heißen/heißt.ogg">🔊</span> |
| er heiß**t** <span class="pron" data-src="../audio/verben/heißen/heißt.ogg">🔊</span><br>sie heiß**t**<br>es heiß**t** | Sie heiß**en** <span class="pron" data-src="../audio/verben/heißen/heißen.ogg">🔊</span><br>sie heiß**en** |

## Infinitive stems ending in *-d* or *-t*

Infinitive stems ending in *-d* or *-t* need to have an *-e* added after the infinitive stem but prior to the *-st* or *-t* in order to be able to pronounce it. Some common words that fall into this category are:

| *-d* |*-t* |
|:---:|:---:|
| **baden** <span class="pron" data-src="../audio/verben/baden/baden.ogg">🔊</span> (to bathe) | **arbeiten** <span class="pron" data-src="../audio/verben/arbeiten/arbeiten.ogg">🔊</span> (to work) |
| **schneiden** <span class="pron" data-src="../audio/verben/schneiden/schneiden.ogg">🔊</span> (to cut) | **antworten** <span class="pron" data-src="../audio/verben/antworten/antworten.ogg">🔊</span> (to answer) |
|| **retten** <span class="pron" data-src="../audio/verben/retten/retten.ogg">🔊</span> (to rescue) |
|| **beten** <span class="pron" data-src="../audio/verben/beten/beten.ogg">🔊</span> (to pray) |

Let's see this conjugation in practice:

<div style="text-align: center;">
**baden** <span class="pron" data-src="../audio/verben/baden/baden.ogg">🔊</span> (to bathe)
</div>

|||
|:---:|:---:|
| ich bad**e** <span class="pron" data-src="../audio/verben/baden/bade.ogg">🔊</span> | wir bad**en** <span class="pron" data-src="../audio/verben/baden/baden.ogg">🔊</span> |
| du bad**est** <span class="pron" data-src="../audio/verben/baden/badest.ogg">🔊</span> | ihr bad**et** <span class="pron" data-src="../audio/verben/baden/badet.ogg">🔊</span> |
| er bad**et** <span class="pron" data-src="../audio/verben/baden/badet.ogg">🔊</span> <br>sie bad**et** <br>es bad**et** | Sie bad**en** <span class="pron" data-src="../audio/verben/baden/baden.ogg">🔊</span> <br>sie bad**en** |

<div style="text-align: center;">
**arbeiten** <span class="pron" data-src="../audio/verben/arbeiten/arbeiten.ogg">🔊</span> (to work)
</div>

|||
|:---:|:---:|
| ich arbeit**e** <span class="pron" data-src="../audio/verben/arbeiten/arbeite.ogg">🔊</span> | wir arbeit**en** <span class="pron" data-src="../audio/verben/arbeiten/arbeiten.ogg">🔊</span> |
| du arbeit**est** <span class="pron" data-src="../audio/verben/arbeiten/arbeitest.ogg">🔊</span> | ihr arbeit**et** <span class="pron" data-src="../audio/verben/arbeiten/arbeitet.ogg">🔊</span> |
| er arbeit**et** <span class="pron" data-src="../audio/verben/arbeiten/arbeitet.ogg">🔊</span> <br>sie arbeit**et**<br>es arbeit**et** | Sie arbeit**en** <span class="pron" data-src="../audio/verben/arbeiten/arbeiten.ogg">🔊</span> <br>sie arbeit**en** |

## Infinitive stems ending in *-m* or *-n* preceded by a consonant sound other than *-l* or *-r*

Additionally, if the verb stem ends in an *-m* or *-n* that is preceded by a *consonant sound* other than *-l* or *-r* then we need to add an *-e*, just like the circumstances of infinitive stems ending with *-d* or *-t* above. 

This rule can be a bit difficult for learners because it matters how one defines a "*consonant sound*". Does the sound before the *-m* or *-n* sound like a vowel, *-l* or *r*? If so, it is treated normally. Otherwise, we need to add an *-e*. Let's look at common application of this rule, then look at examples where we need to think about this "*consonant sound*" idea.

<div style="text-align: center;">
**atmen** <span class="pron" data-src="../audio/verben/atmen/atmen.ogg">🔊</span> (to breathe)
</div>

|||
|:---:|:---:|
| ich atm**e** <span class="pron" data-src="../audio/verben/atmen/atme.ogg">🔊</span> | wir atm**en** <span class="pron" data-src="../audio/verben/atmen/atmen.ogg">🔊</span> |
| du atm**est** <span class="pron" data-src="../audio/verben/atmen/atmest.ogg">🔊</span> | ihr atm**et** <span class="pron" data-src="../audio/verben/atmen/atmet.ogg">🔊</span> |
| er atm**et** <span class="pron" data-src="../audio/verben/atmen/atmet.ogg">🔊</span><br>sie atm**et**<br>es atm**et** | Sie atm**en** <span class="pron" data-src="../audio/verben/atmen/atmen.ogg">🔊</span><br>sie atm**en** |

<div style="text-align: center;">
**öffnen** <span class="pron" data-src="../audio/verben/öffnen/öffnen.ogg">🔊</span> (to open)
</div>

|||
|:---:|:---:|
| ich öffn**e** <span class="pron" data-src="../audio/verben/öffnen/öffne.ogg">🔊</span> | wir öffn**en** <span class="pron" data-src="../audio/verben/öffnen/öffnen.ogg">🔊</span> |
| du öffn**est** <span class="pron" data-src="../audio/verben/öffnen/öffnest.ogg">🔊</span> | ihr öffn**et** <span class="pron" data-src="../audio/verben/öffnen/öffnet.ogg">🔊</span> |
| er öffn**et** <span class="pron" data-src="../audio/verben/öffnen/öffnet.ogg">🔊</span><br>sie öffn**et**<br>es öffn**et** | Sie öffn**en** <span class="pron" data-src="../audio/verben/öffnen/öffnen.ogg">🔊</span><br>sie öffn**en** |

A table of common verbs that fall into the category of requiring an *-e* to be added are below:

| *-m* preceded by a consonant sound other than *-l* or *-r* | *-n* preceded by a consonant sound other than *-l* or *-r* |
|:---:|:---:|
| **atmen** <span class="pron" data-src="../audio/verben/atmen/atmen.ogg">🔊</span> (to breathe) | **öffnen** <span class="pron" data-src="../audio/verben/öffnen/öffnen.ogg">🔊</span> (to open) |
|| **rechnen** <span class="pron" data-src="../audio/verben/rechnen/rechnen.ogg">🔊</span> (to calculate) |
|| **zeichnen** <span class="pron" data-src="../audio/verben/zeichnen/zeichnen.ogg">🔊</span> (to draw) |
|| **trocknen** <span class="pron" data-src="../audio/verben/trocknen/trocknen.ogg">🔊</span> (to dry (something)) |

:::{.callout-note}
# Comment on the frequency of this category of verbs
There aren't a ton of verbs that fall into this category. In fact, for the category of having an *-m* preceded by a consonant sound other than *-l* or *-r*, **atmen** <span class="pron" data-src="../audio/verben/atmen/atmen.ogg">🔊</span>, and it's derivatives (**einatmen** <span class="pron" data-src="../audio/verben/einatmen/einatmen.ogg">🔊</span> (to breathe in), **ausatmen** <span class="pron" data-src="../audio/verben/ausatmen/ausatmen.ogg">🔊</span> (to breathe out), **durchatmen** <span class="pron" data-src="../audio/verben/durchatmen/durchatmen.ogg">🔊</span> (to catch your breath), **aufatmen** <span class="pron" data-src="../audio/verben/aufatmen/aufatmen.ogg">🔊</span> (to breathe a sigh of relief), etc.) is the only verb (that I am aware of) that falls into this category.

For infinitive stems with *-n* preceded by a consonant sound other than *-l* or *-r*, it is also quite limited. The table above covers all of the most common ones and a handful of others do exist (**begegnen** <span class="pron" data-src="../audio/verben/begegnen/begegnen.ogg">🔊</span> (to meet (by chance)), **entgegnen** <span class="pron" data-src="../audio/verben/entgegnen/entgegnen.ogg">🔊</span> (to reply (often contradictory)), **segnen** <span class="pron" data-src="../audio/verben/segnen/segnen.ogg">🔊</span> (to bless), etc.), but they are quite infrequent to come across as a beginner.
:::

:::{.callout-note}
# Infinitive stems ending in an *-m* or *-n* that are preceded by vowel sounds, *-l* or *-r* do not add an *-e* to the infinitive stem

To prove the rule, let's look at a few infinitive stems that either end in *-m* or *-n* and are preceded by a vowel sound, *-l* or *-r*. 

<div style="text-align: center;">
**lernen** <span class="pron" data-src="../audio/verben/lernen/lernen.ogg">🔊</span> (to learn)
</div>

|||
|:---:|:---:|
| ich lern**e** <span class="pron" data-src="../audio/verben/lernen/lerne.ogg">🔊</span> | wir lern**en** <span class="pron" data-src="../audio/verben/lernen/lernen.ogg">🔊</span> |
| du lern**st** <span class="pron" data-src="../audio/verben/lernen/lernst.ogg">🔊</span> | ihr lern**t** <span class="pron" data-src="../audio/verben/lernen/lernt.ogg">🔊</span> |
| er lern**t** <span class="pron" data-src="../audio/verben/lernen/lernt.ogg">🔊</span><br>sie lern**t**<br>es lern**t** | Sie lern**en** <span class="pron" data-src="../audio/verben/lernen/lernen.ogg">🔊</span><br>sie lern**en** |

<div style="text-align: center;">
**wärmen** <span class="pron" data-src="../audio/verben/wärmen/wärmen.ogg">🔊</span> (to warm)
</div>

|||
|:---:|:---:|
| ich wärm**e** <span class="pron" data-src="../audio/verben/wärmen/wärme.ogg">🔊</span> | wir wärm**en** <span class="pron" data-src="../audio/verben/wärmen/wärmen.ogg">🔊</span> |
| du wärm**st** <span class="pron" data-src="../audio/verben/wärmen/wärmst.ogg">🔊</span> | ihr wärm**t** <span class="pron" data-src="../audio/verben/wärmen/wärmt.ogg">🔊</span> |
| er wärm**t** <span class="pron" data-src="../audio/verben/wärmen/wärmt.ogg">🔊</span><br>sie wärm**t**<br>es wärm**t** | Sie wärm**en** <span class="pron" data-src="../audio/verben/wärmen/wärmen.ogg">🔊</span><br>sie wärm**en** |

Unlike the infinitive stems ending in *-m* or *-n* preceded by a consonant sound other than *l* or *r*, these are relatively more common. I have provided a list below of some of the more common ones you might come across:

::: columns
::: column
- **beginnen** <span class="pron" data-src="../audio/verben/beginnen/beginnen.ogg">🔊</span> (to begin)
- **sich besinnen** <span class="pron" data-src-list="../audio/reflexive/sich.ogg, ../audio/verben/besinnen/besinnen.ogg">🔊</span> (to recollect / to think better of)
- **brennen** <span class="pron" data-src="../audio/verben/brennen/brennen.ogg">🔊</span> (to burn)
- **dienen** <span class="pron" data-src="../audio/verben/dienen/dienen.ogg">🔊</span> (to serve (a cause))
- **entfernen** <span class="pron" data-src="../audio/verben/entfernen/entfernen.ogg">🔊</span> (to remove (something))
- **erwähnen** <span class="pron" data-src="../audio/verben/erwähnen/erwähnen.ogg">🔊</span> (to mention)
- **filmen** <span class="pron" data-src="../audio/verben/filmen/filmen.ogg">🔊</span> (to film)
:::

::: column
- **sich gewöhnen**\* <span class="pron" data-src-list="../audio/reflexive/sich.ogg, ../audio/verben/gewöhnen/gewöhnen.ogg">🔊</span> (to become accustomed)
- **kennenlernen** <span class="pron" data-src="../audio/verben/kennenlernen/kennenlernen.ogg">🔊</span> (to get to know/to meet)
- **kommen** <span class="pron" data-src="../audio/verben/kommen/kommen.ogg">🔊</span> (to come)
- **lernen** <span class="pron" data-src="../audio/verben/lernen/lernen.ogg">🔊</span> (to learn)
- **meinen** <span class="pron" data-src="../audio/verben/meinen/meinen.ogg">🔊</span> (to mean)
- **wärmen** <span class="pron" data-src="../audio/verben/wärmen/wärmen.ogg">🔊</span> (to warm)
- **wohnen**\* <span class="pron" data-src="../audio/verben/wohnen/wohnen.ogg">🔊</span> (to reside (somewhere))
:::
:::

\* *Note in these examples that the -n is preceded by an -h and you may be inclined to think that these are breaking the rule. However, in this context, the sound prior to the -n still has a "vowel-like" sound. This is part of the reason why this rule is the tricky.*

I am also not aware of any circumstances where the infinitive stem has a *-ln* pattern and **filmen** is the only one I know with the *-lm* pattern.

:::


# Infinitives ending in *-n* rather than *-en*

Most verbs in German end in *-en*, but there are a handful that rather end with just an *-n*. In order to conjugate these verbs, treat the *-n* as if it were *-en*, by removing it and adding the normal endings. Some examples from this group of verbs are:

:::columns
:::column
- **ändern** <span class="pron" data-src="../audio/verben/ändern/ändern.ogg">🔊</span> (to change)
- **erinnern** <span class="pron" data-src="../audio/verben/erinnern/erinnern.ogg">🔊</span> (to remember)
- **handeln** <span class="pron" data-src="../audio/verben/handeln/handeln.ogg">🔊</span> (to trade)
- **lächeln** <span class="pron" data-src="../audio/verben/lächeln/lächeln.ogg">🔊</span> (to smile)
:::

:::column
- **sammeln** <span class="pron" data-src="../audio/verben/sammeln/sammeln.ogg">🔊</span> (to collect)
- **segeln** <span class="pron" data-src="../audio/verben/segeln/segeln.ogg">🔊</span> (to sail)
- **wechseln** <span class="pron" data-src="../audio/verben/wechseln/wechseln.ogg">🔊</span> (to change or to exchange)
:::
:::

We can see an example for how to conjugate these verbs:

<div style="text-align: center;">
**segeln** <span class="pron" data-src="../audio/verben/segeln/segeln.ogg">🔊</span> (to sail)
</div>

|||
|:---:|:---:|
| ich segel**e** <span class="pron" data-src="../audio/verben/segeln/segele.ogg">🔊</span>  | wir segel**n** <span class="pron" data-src="../audio/verben/segeln/segeln.ogg">🔊</span>  |
| du segel**st** <span class="pron" data-src="../audio/verben/segeln/segelst.ogg">🔊</span>  | ihr segel**t** <span class="pron" data-src="../audio/verben/segeln/segelt.ogg">🔊</span> |
| er segel**t** <span class="pron" data-src="../audio/verben/segeln/segelt.ogg">🔊</span> <br>sie segel**t**<br>es segel**t** | Sie segel**n** <span class="pron" data-src="../audio/verben/segeln/segeln.ogg">🔊</span><br>sie segel**n** |

:::{.callout-note}
## Colloquial form in the first-person singular
You will sometimes see the *-e* preceding the *-ln* at the end of the verb dropped in the first-person singular. In this case, a verb like **segeln** would look like:

<div style="text-align: center;">
**segeln** <span class="pron" data-src="../audio/verben/segeln/segeln.ogg">🔊</span> (to sail)
</div>

|||
|:---:|:---:|
| ich segl**e** <span class="pron" data-src="../audio/verben/segeln/segle.ogg">🔊</span> | wir segel**n** <span class="pron" data-src="../audio/verben/segeln/segeln.ogg">🔊</span> |
| du segel**st** <span class="pron" data-src="../audio/verben/segeln/segelst.ogg">🔊</span> | ihr segel**t** <span class="pron" data-src="../audio/verben/segeln/segelt.ogg">🔊</span> |
| er segel**t**<span class="pron" data-src="../audio/verben/segeln/segelt.ogg">🔊</span><br>sie segel**t**<br>es segel**t** | Sie segel**n**<span class="pron" data-src="../audio/verben/segeln/segeln.ogg">🔊</span><br>sie segel**n** |

[Both spellings](https://www.duden.de/konjugation/segeln) are permitted by Duden, the *de facto* German dictionary.

:::

:::{.callout-note}
## A consequence of most of these verbs ending in *-eln* and *-ern*
One small thing to note about these verbs is they all end in *-ern* or *-eln*, so you don't need to worry about the above circumstances where the verb has a stem that ends in *-d*, *-m*, *-n*, *-s*, *-t*, *-ß*, *-x* or *-z* once you remove the *-n*.
:::

:::{.callout-note}
## Excluding **sein** and **tun** from this category
One could argue that **sein** (to be) **tun** (to do) also end in *-n* rather than *-en*, but since they are both irregular verbs, so we will handle them elsewhere.
:::

# Stem-changing verbs

Some verbs change their stem in the second-person singular and the third-person singular. Unfortunately, there aren't any tricks or mnemonics for recognizing which ones do stem change, which ones don't. However, the good news is that many are used frequently enough that you will likely learn the most common offenders quickly. There are three classes of stem-changing verbs:

- a → ä
- e → i
- e → ie

Each of the tabsets below provides an example for how each class of these stem-changing verbs is conjugated:

:::{.panel-tabset group="stem_changing"}
## a → ä
<div style="text-align: center;">
**laufen** <span class="pron" data-src="../audio/verben/laufen/laufen.ogg">🔊</span> (to walk or to run)
</div>

|||
|:---:|:---:|
| ich lauf**e** <span class="pron" data-src="../audio/verben/laufen/laufe.ogg">🔊</span> | wir lauf**en** <span class="pron" data-src="../audio/verben/laufen/laufen.ogg">🔊</span> |
| du l**ä**uf**st** <span class="pron" data-src="../audio/verben/laufen/läufst.ogg">🔊</span> | ihr lauf**t** <span class="pron" data-src="../audio/verben/laufen/lauft.ogg">🔊</span> |
| er l**ä**uf**t** <span class="pron" data-src="../audio/verben/laufen/läuft.ogg">🔊</span><br>sie l**ä**uf**t**<br>es l**ä**uf**t** | Sie lauf**en** <span class="pron" data-src="../audio/verben/laufen/laufen.ogg">🔊</span><br>sie lauf**en** |

## e → i
<div style="text-align: center;">
**geben** <span class="pron" data-src="../audio/verben/geben/geben.ogg">🔊</span> (to give)
</div>

|||
|:---:|:---:|
| ich geb**e** <span class="pron" data-src="../audio/verben/geben/gebe.ogg">🔊</span> | wir geb**en** <span class="pron" data-src="../audio/verben/geben/geben.ogg">🔊</span> |
| du g**i**b**st** <span class="pron" data-src="../audio/verben/geben/gibst.ogg">🔊</span> | ihr geb**t** <span class="pron" data-src="../audio/verben/geben/gebt.ogg">🔊</span> |
| er g**i**b**t** <span class="pron" data-src="../audio/verben/geben/gibt.ogg">🔊</span><br>sie g**i**b**t**<br>es g**i**b**t** | Sie geb**en** <span class="pron" data-src="../audio/verben/geben/geben.ogg">🔊</span><br>sie geb**en** |

## e → ie
<div style="text-align: center;">
**sehen** <span class="pron" data-src="../audio/verben/sehen/sehen.ogg">🔊</span> (to see)
</div>

|||
|:---:|:---:|
| ich seh**e** <span class="pron" data-src="../audio/verben/sehen/sehe.ogg">🔊</span> | wir seh**en** <span class="pron" data-src="../audio/verben/sehen/sehen.ogg">🔊</span> |
| du s**ie**h**st** <span class="pron" data-src="../audio/verben/sehen/siehst.ogg">🔊</span> | ihr seh**t** <span class="pron" data-src="../audio/verben/sehen/seht.ogg">🔊</span> |
| er s**ie**h**t** <span class="pron" data-src="../audio/verben/sehen/sieht.ogg">🔊</span><br>sie s**ie**h**t**<br>es s**ie**h**t** | Sie seh**en** <span class="pron" data-src="../audio/verben/sehen/sehen.ogg">🔊</span><br>sie seh**en** |

:::

More examples of stem-changing verbs from each class can be found in the tabset below: 

:::{.panel-tabset group="stem_changing"}
## a → ä

:::columns
:::column
- **fahren** <span class="pron" data-src="../audio/verben/fahren/fahren.ogg">🔊</span> (to drive or to travel)
- **fallen** <span class="pron" data-src="../audio/verben/fallen/fallen.ogg">🔊</span> (to fall)
- **lassen** <span class="pron" data-src="../audio/verben/lassen/lassen.ogg">🔊</span> (to let or to leave)
- **laufen** <span class="pron" data-src="../audio/verben/laufen/laufen.ogg">🔊</span> (to walk or to run)
:::

:::column
- **schlafen** <span class="pron" data-src="../audio/verben/schlafen/schlafen.ogg">🔊</span> (to sleep)
- **schlagen** <span class="pron" data-src="../audio/verben/schlagen/schlagen.ogg">🔊</span> (to hit)
- **tragen** <span class="pron" data-src="../audio/verben/tragen/tragen.ogg">🔊</span> (to wear)
- **waschen** <span class="pron" data-src="../audio/verben/waschen/waschen.ogg">🔊</span> (to wash)
:::
:::

## e → i

:::columns
:::column
- **essen** <span class="pron" data-src="../audio/verben/essen/essen.ogg">🔊</span> (to eat)
- **geben** <span class="pron" data-src="../audio/verben/geben/geben.ogg">🔊</span> (to give)
- **helfen** <span class="pron" data-src="../audio/verben/helfen/helfen.ogg">🔊</span> (to help)
:::

:::column
- **sprechen** <span class="pron" data-src="../audio/verben/sprechen/sprechen.ogg">🔊</span> (to speak)
- **treffen** <span class="pron" data-src="../audio/verben/treffen/treffen.ogg">🔊</span> (to meet someone you are familiar with)
:::
:::

## e → ie

:::columns
:::column
- **empfehlen** <span class="pron" data-src="../audio/verben/empfehlen/empfehlen.ogg">🔊</span> (to recommend)
- **lesen** <span class="pron" data-src="../audio/verben/lesen/lesen.ogg">🔊</span> (to read)
:::

:::column
- **sehen** <span class="pron" data-src="../audio/verben/sehen/sehen.ogg">🔊</span> (to see)
- **stehlen** <span class="pron" data-src="../audio/verben/stehlen/stehlen.ogg">🔊</span> (to steal)
:::
:::

:::

# Stem-changing verbs with *-t* infinitive stem-endings

There is a very small group of verbs who have to deal with the interaction between being a stem-changing verb and having an infinitive stem ending in *-t*. This group of verb has a very particular behavior. In the second- and third-person singular, they will undergo their stem-change, but the endings are a bit different. The second-person singular will directly add the *-st* after the infinitive stem, forgoing adding the additional *-e* that we would traditionally add when handling verbs with infinitive stems ending in *-t*. The third person singular just leaves the infinitive stem and adds no ending. 

Since the stem-changing effect doesn't occur in the second-person person plural, we still need to add the *-e* prior to the *-t*.

Let's look at a common example of this in **halten**:

<div style="text-align: center;">
**halten** <span class="pron" data-src="../audio/verben/halten/halten.ogg">🔊</span> (to hold/to maintain a state/to stop)
</div>

|||
|:---:|:---:|
| ich halt**e** <span class="pron" data-src="../audio/verben/halten/halte.ogg">🔊</span> | wir halt**en** <span class="pron" data-src="../audio/verben/halten/halten.ogg">🔊</span> |
| du h**ä**lt**st** <span class="pron" data-src="../audio/verben/halten/hältst.ogg">🔊</span> | ihr halt**et** <span class="pron" data-src="../audio/verben/halten/haltet.ogg">🔊</span> |
| er h**ä**lt <span class="pron" data-src="../audio/verben/halten/hält.ogg">🔊</span><br>sie h**ä**lt<br>es h**ä**lt | Sie halt**en** <span class="pron" data-src="../audio/verben/halten/halten.ogg">🔊</span><br>sie halt**en** |

The verbs that fall into this category are in the tabset below:

:::{.panel-tabset}
## a → ä
- **braten** <span class="pron" data-src="../audio/verben/braten/braten.ogg">🔊</span> (to pan-fry/to grill)
- **geraten** <span class="pron" data-src="../audio/verben/geraten/geraten.ogg">🔊</span> (to get into/to fall into)
- **halten** <span class="pron" data-src="../audio/verben/halten/halten.ogg">🔊</span> (to hold/to maintain a state/to stop)
- **raten** <span class="pron" data-src="../audio/verben/raten/raten.ogg">🔊</span> (to advise)

## e → i
- **gelten** <span class="pron" data-src="../audio/verben/gelten/gelten.ogg">🔊</span> (to be valid/to be regarded)

:::

::: {.callout-note}
## What about e → ie?

You might notice that in the above tabset, we don't have a tab for e → ie stem-changing verbs and that is because e → ie stem changing verbs are rare and those that do exist, don't have a infinitive stem ending of *-t*.

:::

::: {.callout-note}
## What about *-d* infinitive stem endings?

This rule is limited to the stem-changing verbs with *-t* infinitive stem endings, because I am unaware of any stem-changing verbs that have an infinitive stem ending of *-d*, besides **laden** (to load), which has a strange enough conjugation to warrant placing it in the irregular category.

:::


# Irregular conjugations

In addition to **sein**, there are a handful of irregular verbs that don't fall neatly into any of the above categories. Many of these are used frequently, so you will likely learn that they are different rather quickly. A brief list of the most common ones are: 

:::columns
:::column
- **dürfen** <span class="pron" data-src="../audio/verben/dürfen/dürfen.ogg">🔊</span> (to allow/to permit/may)
- **gebären** <span class="pron" data-src="../audio/verben/gebären/gebären.ogg">🔊</span> (to give birth to)
- **haben** <span class="pron" data-src="../audio/verben/haben/haben.ogg">🔊</span> (to have)
- **können** <span class="pron" data-src="../audio/verben/können/können.ogg">🔊</span> (to be able to/can)
- **laden** <span class="pron" data-src="../audio/verben/laden/laden.ogg">🔊</span> (to load)
- **mögen** <span class="pron" data-src="../audio/verben/mögen/mögen.ogg">🔊</span> (to like)
- **müssen** <span class="pron" data-src="../audio/verben/müssen/müssen.ogg">🔊</span> (to have to/must)
- **nehmen** <span class="pron" data-src="../audio/verben/nehmen/nehmen.ogg">🔊</span> (to take)
:::

:::column
- **sein** <span class="pron" data-src="../audio/verben/sein/sein.ogg">🔊</span> (to be)
- **sollen** <span class="pron" data-src="../audio/verben/sollen/sollen.ogg">🔊</span> (is supposed to be/is allegedly)
- **treten** <span class="pron" data-src="../audio/verben/treten/treten.ogg">🔊</span> (to tread/to kick)
- **tun** <span class="pron" data-src="../audio/verben/tun/tun.ogg">🔊</span> (to do)
- **werden** <span class="pron" data-src="../audio/verben/werden/werden.ogg">🔊</span> (to become)
- **wissen** <span class="pron" data-src="../audio/verben/wissen/wissen.ogg">🔊</span> (to know, as in facts)
- **wollen** <span class="pron" data-src="../audio/verben/wollen/wollen.ogg">🔊</span> (to want)
:::
:::

There are conjugation tables for each of these verbs in the tabsets below:

:::{.panel-tabset}
## dürfen
<div style="text-align: center;">
**dürfen** <span class="pron" data-src="../audio/verben/dürfen/dürfen.ogg">🔊</span> (to allow/to permit/may)
</div>

|||
|:---:|:---:|
| ich d**a**rf <span class="pron" data-src="../audio/verben/dürfen/darf.ogg">🔊</span> | wir dürf**en** <span class="pron" data-src="../audio/verben/dürfen/dürfen.ogg">🔊</span> |
| du d**a**rf**st** <span class="pron" data-src="../audio/verben/dürfen/darfst.ogg">🔊</span> | ihr dürf**t** <span class="pron" data-src="../audio/verben/dürfen/dürft.ogg">🔊</span> |
| er d**a**rf <span class="pron" data-src="../audio/verben/dürfen/darf.ogg">🔊</span><br>sie d**a**rf<br>es d**a**rf | Sie dürf**en** <span class="pron" data-src="../audio/verben/dürfen/dürfen.ogg">🔊</span><br>sie dürf**en** |

## gebären
<div style="text-align: center;">
**gebären** <span class="pron" data-src="../audio/verben/gebären/gebären.ogg">🔊</span> (to give birth to)
</div>

|||
|:---:|:---:|
| ich gebär**e** <span class="pron" data-src="../audio/verben/gebären/gebäre.ogg">🔊</span> | wir gebär**en** <span class="pron" data-src="../audio/verben/gebären/gebären.ogg">🔊</span> |
| du geb**ie**r**st** <span class="pron" data-src="../audio/verben/gebären/gebierst.ogg">🔊</span> | ihr gebär**t** <span class="pron" data-src="../audio/verben/gebären/gebärt.ogg">🔊</span> |
| er geb**ie**r**t** <span class="pron" data-src="../audio/verben/gebären/gebiert.ogg">🔊</span><br>sie geb**ie**r**t**<br>es geb**ie**r**t** | Sie gebär**en** <span class="pron" data-src="../audio/verben/gebären/gebären.ogg">🔊</span><br>sie gebär**en** |


## haben
<div style="text-align: center;">
**haben** <span class="pron" data-src="../audio/verben/haben/haben.ogg">🔊</span> (to have)
</div>

|||
|:---:|:---:|
| ich hab**e** <span class="pron" data-src="../audio/verben/haben/habe.ogg">🔊</span> | wir hab**en** <span class="pron" data-src="../audio/verben/haben/haben.ogg">🔊</span> |
| du ha**st** <span class="pron" data-src="../audio/verben/haben/hast.ogg">🔊</span> | ihr hab**t** <span class="pron" data-src="../audio/verben/haben/habt.ogg">🔊</span> |
| er ha**t** <span class="pron" data-src="../audio/verben/haben/hat.ogg">🔊</span><br>sie ha**t**<br>es ha**t** | Sie hab**en** <span class="pron" data-src="../audio/verben/haben/haben.ogg">🔊</span><br>sie hab**en** |

## können
<div style="text-align: center;">
**können** <span class="pron" data-src="../audio/verben/können/können.ogg">🔊</span> (to be able to/can)
</div>

|||
|:---:|:---:|
| ich k**a**nn <span class="pron" data-src="../audio/verben/können/kann.ogg">🔊</span> | wir könn**en** <span class="pron" data-src="../audio/verben/können/können.ogg">🔊</span> |
| du k**a**nn**st** <span class="pron" data-src="../audio/verben/können/kannst.ogg">🔊</span> | ihr könn**t** <span class="pron" data-src="../audio/verben/können/könnt.ogg">🔊</span> |
| er k**a**nn <span class="pron" data-src="../audio/verben/können/kann.ogg">🔊</span><br>sie k**a**nn<br>es k**a**nn | Sie könn**en** <span class="pron" data-src="../audio/verben/können/können.ogg">🔊</span><br>sie könn**en** |

## laden
<div style="text-align: center;">
**laden** <span class="pron" data-src="../audio/verben/laden/laden.ogg">🔊</span> (to load)
</div>

|||
|:---:|:---:|
| ich lad**e** <span class="pron" data-src="../audio/verben/laden/lade.ogg">🔊</span> | wir lad**en** <span class="pron" data-src="../audio/verben/laden/laden.ogg">🔊</span> |
| du l**ä**d**st** <span class="pron" data-src="../audio/verben/laden/lädst.ogg">🔊</span> | ihr lad**et** <span class="pron" data-src="../audio/verben/laden/ladet.ogg">🔊</span> |
| er l**ä**d**t** <span class="pron" data-src="../audio/verben/laden/lädt.ogg">🔊</span><br>sie l**ä**d**t**<br>es l**ä**d**t** | Sie lad**en** <span class="pron" data-src="../audio/verben/laden/laden.ogg">🔊</span><br>sie lad**en** |

We can see that **laden** behaves very similarly to the stem-changing verbs ending in *-t*. However, in the third person singular, it adds *-t* to the end, which that set of verbs do not do. As such, I group it with the irregular verbs.

## mögen
<div style="text-align: center;">
**mögen** <span class="pron" data-src="../audio/verben/mögen/mögen.ogg">🔊</span> (to like)
</div>

|||
|:---:|:---:|
| ich m**a**g <span class="pron" data-src="../audio/verben/mögen/mag.ogg">🔊</span> | wir mög**en** <span class="pron" data-src="../audio/verben/mögen/mögen.ogg">🔊</span> |
| du m**a**g**st** <span class="pron" data-src="../audio/verben/mögen/magst.ogg">🔊</span> | ihr mög**t** <span class="pron" data-src="../audio/verben/mögen/mögt.ogg">🔊</span> |
| er m**a**g <span class="pron" data-src="../audio/verben/mögen/mag.ogg">🔊</span><br>sie m**a**g<br>es m**a**g | Sie mög**en** <span class="pron" data-src="../audio/verben/mögen/mögen.ogg">🔊</span><br>sie mög**en** |

## müssen
<div style="text-align: center;">
**müssen** <span class="pron" data-src="../audio/verben/müssen/müssen.ogg">🔊</span> (to have to/must)
</div>

|||
|:---:|:---:|
| ich m**u**ss <span class="pron" data-src="../audio/verben/müssen/muss.ogg">🔊</span> | wir müss**en** <span class="pron" data-src="../audio/verben/müssen/müssen.ogg">🔊</span> |
| du m**u**ss**t** <span class="pron" data-src="../audio/verben/müssen/musst.ogg">🔊</span> | ihr müss**t** <span class="pron" data-src="../audio/verben/müssen/müsst.ogg">🔊</span> |
| er m**u**ss <span class="pron" data-src="../audio/verben/müssen/muss.ogg">🔊</span><br>sie m**u**ss<br>es m**u**ss | Sie müss**en** <span class="pron" data-src="../audio/verben/müssen/müssen.ogg">🔊</span><br>sie müss**en** |

## nehmen
<div style="text-align: center;">
**nehmen** <span class="pron" data-src="../audio/verben/nehmen/nehmen.ogg">🔊</span> (to take)
</div>

|||
|:---:|:---:|
| ich nehm**e** <span class="pron" data-src="../audio/verben/nehmen/nehme.ogg">🔊</span> | wir nehm**en** <span class="pron" data-src="../audio/verben/nehmen/nehmen.ogg">🔊</span> |
| du n**im**m**st** <span class="pron" data-src="../audio/verben/nehmen/nimmst.ogg">🔊</span> | ihr nehm**t** <span class="pron" data-src="../audio/verben/nehmen/nehmt.ogg">🔊</span> |
| er n**im**m**t** <span class="pron" data-src="../audio/verben/nehmen/nimmt.ogg">🔊</span><br>sie n**im**m**t**<br>es n**im**m**t** | Sie nehm**en** <span class="pron" data-src="../audio/verben/nehmen/nehmen.ogg">🔊</span><br>sie nehm**en** |

## sein
<div style="text-align: center;">
**sein** <span class="pron" data-src="../audio/verben/sein/sein.ogg">🔊</span> (to be) 
</div>

|||
|:---:|:---:|
| ich **bin** <span class="pron" data-src="../audio/verben/sein/bin.ogg">🔊</span> | wir **sind** <span class="pron" data-src="../audio/verben/sein/sind.ogg">🔊</span> |
| du **bist** <span class="pron" data-src="../audio/verben/sein/bist.ogg">🔊</span> | ihr **seid** <span class="pron" data-src="../audio/verben/sein/seid.ogg">🔊</span> |
| er **ist** <span class="pron" data-src="../audio/verben/sein/ist.ogg">🔊</span> <br>sie **ist**<br>es **ist** | Sie **sind** <span class="pron" data-src="../audio/verben/sein/sind.ogg">🔊</span><br>sie **sind** |

## sollen
<div style="text-align: center;">
**sollen** <span class="pron" data-src="../audio/verben/sollen/sollen.ogg">🔊</span> (is supposed to be/is allegedly)
</div>

|||
|:---:|:---:|
| ich soll <span class="pron" data-src="../audio/verben/sollen/soll.ogg">🔊</span> | wir soll**en** <span class="pron" data-src="../audio/verben/sollen/sollen.ogg">🔊</span> |
| du soll**st** <span class="pron" data-src="../audio/verben/sollen/sollst.ogg">🔊</span> | ihr soll**t** <span class="pron" data-src="../audio/verben/sollen/sollt.ogg">🔊</span> |
| er soll <span class="pron" data-src="../audio/verben/sollen/soll.ogg">🔊</span><br>sie soll<br>es soll | Sie soll**en** <span class="pron" data-src="../audio/verben/sollen/sollen.ogg">🔊</span><br>sie soll**en** |

## treten
<div style="text-align: center;">
**treten** <span class="pron" data-src="../audio/verben/treten/treten.ogg">🔊</span> (to tread/to kick)
</div>

|||
|:---:|:---:|
| ich tret**e** <span class="pron" data-src="../audio/verben/treten/trete.ogg">🔊</span> | wir tret**en** <span class="pron" data-src="../audio/verben/treten/treten.ogg">🔊</span> |
| du tr**i**t**tst** <span class="pron" data-src="../audio/verben/treten/trittst.ogg">🔊</span> | ihr tret**et** <span class="pron" data-src="../audio/verben/treten/tretet.ogg">🔊</span> |
| er tr**i**t**t** <span class="pron" data-src="../audio/verben/treten/tritt.ogg">🔊</span><br>sie tr**i**t**t**<br>es tr**i**t**t** | Sie tret**en** <span class="pron" data-src="../audio/verben/treten/treten.ogg">🔊</span><br>sie tret**en** |

The verb **treten** is very similar to the stem-changing verbs that end in *-t*, but for some reason it adds an extra *-t* onto the infinitive stem in the second- and third-person singular. As such, I group it with the irregulars.

## tun
<div style="text-align: center;">
**tun** <span class="pron" data-src="../audio/verben/tun/tun.ogg">🔊</span> (to do)
</div>

|||
|:---:|:---:|
| ich tu**e** <span class="pron" data-src="../audio/verben/tun/tue.ogg">🔊</span> | wir **tun** <span class="pron" data-src="../audio/verben/tun/tun.ogg">🔊</span> |
| du tu**st** <span class="pron" data-src="../audio/verben/tun/tust.ogg">🔊</span> | ihr tu**t** <span class="pron" data-src="../audio/verben/tun/tut.ogg">🔊</span> |
| er tu**t** <span class="pron" data-src="../audio/verben/tun/tut.ogg">🔊</span><br>sie tu**t**<br>es tu**t** | Sie **tun** <span class="pron" data-src="../audio/verben/tun/tun.ogg">🔊</span><br>sie **tun** |

## werden
<div style="text-align: center;">
**werden** <span class="pron" data-src="../audio/verben/werden/werden.ogg">🔊</span> (to become)
</div>

|||
|:---:|:---:|
| ich werd**e** <span class="pron" data-src="../audio/verben/werden/werde.ogg">🔊</span> | wir werd**en** <span class="pron" data-src="../audio/verben/werden/werden.ogg">🔊</span> |
| du w**i**r**st** <span class="pron" data-src="../audio/verben/werden/wirst.ogg">🔊</span> | ihr werd**et** <span class="pron" data-src="../audio/verben/werden/werdet.ogg">🔊</span> |
| er w**i**rd <span class="pron" data-src="../audio/verben/werden/wird.ogg">🔊</span><br>sie w**i**rd<br>es w**i**rd | Sie werd**en** <span class="pron" data-src="../audio/verben/werden/werden.ogg">🔊</span><br>sie werd**en** |

## wissen
<div style="text-align: center;">
**wissen** <span class="pron" data-src="../audio/verben/wissen/wissen.ogg">🔊</span> (to know, as in facts)
</div>

|||
|:---:|:---:|
| ich w**eiß** <span class="pron" data-src="../audio/verben/wissen/weiß.ogg">🔊</span> | wir wiss**en** <span class="pron" data-src="../audio/verben/wissen/wissen.ogg">🔊</span> |
| du w**eißt** <span class="pron" data-src="../audio/verben/wissen/weißt.ogg">🔊</span> | ihr wiss**t** <span class="pron" data-src="../audio/verben/wissen/wisst.ogg">🔊</span> |
| er w**eiß** <span class="pron" data-src="../audio/verben/wissen/weiß.ogg">🔊</span><br>sie w**eiß**<br>es w**eiß** | Sie wiss**en** <span class="pron" data-src="../audio/verben/wissen/wissen.ogg">🔊</span><br>sie wiss**en** |

## wollen
<div style="text-align: center;">
**wollen** <span class="pron" data-src="../audio/verben/wollen/wollen.ogg">🔊</span> (to want)
</div>

|||
|:---:|:---:|
| ich w**i**ll <span class="pron" data-src="../audio/verben/wollen/will.ogg">🔊</span> | wir woll**en** <span class="pron" data-src="../audio/verben/wollen/wollen.ogg">🔊</span> |
| du w**i**ll**st** <span class="pron" data-src="../audio/verben/wollen/willst.wav">🔊</span> | ihr woll**t** <span class="pron" data-src="../audio/verben/wollen/wollt.ogg">🔊</span> |
| er w**i**ll <span class="pron" data-src="../audio/verben/wollen/will.ogg">🔊</span><br>sie w**i**ll<br>es w**i**ll | Sie woll**en** <span class="pron" data-src="../audio/verben/wollen/wollen.ogg">🔊</span><br>sie woll**en** |

:::

# Impersonal Verbs

There are a handful of verbs that really only exist in the third-person. All of them deal either defining the state of something or are weather-related. People are unable to *do* these verbs and, therefore, they are referred to as ***impersonal verbs***. Some examples are in the tabset below:

:::{.panel-tabset}
## Define the state of something

Some impersonal verbs which define the status of a thing or an event are:

:::columns
:::column
- **stattfinden** <span class="pron" data-src="../audio/verben/stattfinden/stattfinden.ogg">🔊</span> (to happen/to take place)
- **passieren** <span class="pron" data-src="../audio/verben/passieren/passieren.ogg">🔊</span> (to happen)
- **eilen** <span class="pron" data-src="../audio/verben/eilen/eilen.ogg">🔊</span> (to be urgent)
:::

:::column
- **stimmen** <span class="pron" data-src="../audio/verben/stimmen/stimmen.ogg">🔊</span> (to be true)
- **sich lohnen**\* <span class="pron" data-src-list="../audio/reflexive/sich.ogg, ../audio/verben/lohnen/lohnen.ogg">🔊</span> (to be worth it)
:::
:::

## Weather-related verbs

Other impersonal verbs fall within the category of being weather-related, such as:

:::columns
:::column
- **blitzen\*** <span class="pron" data-src="../audio/verben/blitzen/blitzen.ogg">🔊</span> (to lightning)
- **donnern\*** <span class="pron" data-src="../audio/verben/donnern/donnern.ogg">🔊</span> (to thunder)
- **hageln** <span class="pron" data-src="../audio/verben/hageln/hageln.ogg">🔊</span> (to hail)
:::

:::column
- **regnen** <span class="pron" data-src="../audio/verben/regnen/regnen.ogg">🔊</span> (to rain)
- **schneien** <span class="pron" data-src="../audio/verben/schneien/schneien.ogg">🔊</span> (to snow)
:::
:::

\* *Note that these verbs in the context of weather, only have third-person conjugations, but they do have alternative meanings that can be conjugated in the first- and second- person. See the collapsible discussion below for more information.*

:::

As you can see, these are all verbs that people can't "do". *You* can't rain, *I* can't be true and *we* can't happen, but *it* can hail, be true or happen. These impersonal verbs exist in third-person singular and plural.


You might wonder how the weather-related impersonal verbs can occur in the third-person plural. When they are used in the weather-related context, they are usually referring to the things that are coming from the sky, the hailstones, raindrops, snowflakes, etcetera. For example:

- **Die Hagelkörner hageln gegen das Fenster.** - *The hailstones are hailing against the window.*
- **Flocken schneien vom Himmel.** - *The snowflakes are snowing from the sky.*
- **Regenschauer regnen auf die Stadt nieder.** - *Rain showers are raining down on the city.*

However, in most instances you'll run into these weather-related impersonal verbs in the third-person singular:

- **Es hagelt.** - *It is hailing.*
- **Es schneit.** - *It is snowing.*
- **Es regnet** - *It is raining*

::: {.callout-note collapse="true"}
## Prefixes with *schneien*, which change the meaning

There are separable prefixes that can be added to **schneien** (rein‑ / herein‑ / vorbei‑), which change the meaning from "to snow" to "to stop by (casually/unexpectedly)". As a result, these can exist in first- and second-person and you may seen them in a sentence like:

- **Ich schneie später rein.** - *I am stopping by later.*

:::

:::{.callout-note collapse="true"}
## Additional definitions for *blitzen* and *donnern*

Since **blitzen** (to lightning) and **donnern** (to thunder) are weather-related verbs, you may be tempted to not concern yourself with them in the first- and second-person. And in the context of weather-related events, they do act as impersonal verbs since *we* can't lightning or *you* can't thunder (in the weather sense). However, each of these verbs have a secondary definition that can be used in the first- and second-person without any prefixes (unlike schneien; *see the collapsible discussion above*). For **blitzen**, it can refer to flashing one's eyes. For **donnern**, like English, it can also mean to make loud noises. The takeaway message is that *not all* weather-related verbs fail to have first- and second-person conjugations. But it is true that these weather-related verbs act as impersonal verbs when discussing weather. However, they aren't impersonal verbs for other definitions. 

:::

::: {.callout-tip title="**Exercise**"}


[Answer Key](03_Present_verb_conjugation_exceptions-Answer_key.qmd)
:::


