---
title: "Present Tense Verb Conjugation - Irregular"
author: "Will Gammerdinger"
date: Saturday, October 25th, 2025
---

Approximate time: 45 minutes

# Learning Objectives

In this lesson, the learner will:

* Conjugate irregular verbs in the present tense

# Sein

*Sein* mean "to be" and it is probably the most difficult verb to conjugate in the present tense because it doesn't follow any particular rules and you need to just memorize its conjugation. The good news is that you will you use it so frequently that it will become second-nature rather quickly. Below is the conjugation table for *Sein*:

|||
|:---:|:---:|
| ich **bin** | wir **sind** |
| du **bist** | ihr **seid** |
| er **ist**<br>sie **ist**<br>es **ist** | Sie **sind**<br>sie **sind** |

# Infinitive stems ending in *-s*, *-ß*, *-x* or *-z*

Infinitive verbs whose stem ends in *-s*, *-ß*, *-x* or *-z* has only uses *-t* in the for the second-person singular. The rationale I use for this is that these infinitive stems already have either an *-s* sound at the end of the stem or a sound that is similar to *-s*. As a result adding an *-st* ending wouldn't be heard any different than *-t*. Some common words that fall into this category are:

| *-s* |*-ß* |*-x* |*-z* |
|:---:|:---:|:---:|:---:|
| reisen (to travel) | heißen (to be named) | faxen (to fax) | tanzen (to dance) |
||schließen (to close) || sitzen (to sit) |
|| grüßen (to greet) || besitzen (to own) |

This is probably a good place to point out that *-s* and *-ß* related. The *-ß* is sometimes replaced with *-ss*. As such, rules that apply to *-ß*, will also apply to *-s*.

Let's see an example of one of these conjugations:

|||
|:---:|:---:|
| ich heiß**e** | wir heiß**en** |
| du heiß**t** | ihr heiß**t** |
| er heiß**t**<br>sie heiß**t**<br>es heiß**t** | Sie heiß**en**<br>sie heiß**en** |

# Infinitive stems ending in *-n* rather than *-en*

handeln (to trade)
erinnern (to remember)
ändern (to change)
sammeln (to collect)
lächeln (to smile)
segeln (to sail)
wechseln (to change or to exchange)

# Infinitive stems ending in *-d*, *-t* or if it ends in an *-m* or *-n* that is not preceded by an *r*

Infinitive stems ending in *-d*, *-t* or if it ends in an *-m* or *-n* that is not preceded by an *r* have a rather hard sound at the end of the infinitive stem, so we need to have an *e* added after the infinitive stem but prior to the *-st* or *-t* in order to be able to pronounce it. A table of common verbs that fall into this category are below:

| *-d* |*-t* |*-m* not preceded by *r* |*-n* not preceded by *r* |
|:---:|:---:|:---:|:---:|
| baden (to bathe) | arbeiten (to work) | atmen (to breathe) | öffnen (to open) |
| schneiden (to cut) | antworten (to answer) || rechnen (to calculate) |
| laden (to load or to charge) | retten (to rescue) || zeichnen (to draw) |
|| beten (to pray) || regnen (to rain) |


:::{.callout-tip title="Infinitive stems ending in an *-m* or *-n* that is preceded by an *r* are regular verbs"}

Just to prove the rule, let's look at a few infinitive stems that either end in *-m* or *-n* and are preceded by and *l* or an *r*.

lernen (to learn)

|||
|:---:|:---:|
| ich lern**e** | wir lern**en** |
| du lern**st** | ihr lern**t** |
| er lern**t**<br>sie lern**t**<br>es lern**t** | Sie lern**en**<br>sie lern**en** |

wärmen (to warm)

|||
|:---:|:---:|
| ich wärm**e** | wir wärm**en** |
| du wärm**st** | ihr wärm**t** |
| er wärm**t**<br>sie wärm**t**<br>es wärm**t** | Sie wärm**en**<br>sie wärm**en** |

:::

# Stem-changing verbs

## a → ä

- laufen (to walk or to run)
- schlafen (to sleep)
- fahren (to drive or to travel)
- tragen (to wear)
- waschen (to wash)
- lassen (to let or to leave)
- schlagen (to hit)
- fallen (to fall)
- halten (to stop)

## e → i

- essen (to eat)
- geben (to give)
- sprechen (to speak)
- helfen (to help)
- treffen (to meet someone you are familiar with)

## e → ie

- sehen (to see)
- lesen (to read)
- empfehlen (to recommend)
- stehlen (to steal)


# Other strange conjugations

nehmen
haben
wissen
werden

# Verbs that only occur in the third person

There are a handful of verbs that really only exist in the the third-person. All of them deal with events that occur and can't be produced or done by people. They mostly exist in the singular, but can be used more rarely in the plural. Some examples are:

- regnen (to rain)
- schneien (to snow)
- stattfinden (to happen/to take place)

As you can see, these are verbs that people can't "do". *I* can't rain, *you* can't snow and *we* can't happen. But *it* can rain, snow or happen. You might ask how some of these verbs can occur in the third-person plural, and for **regnan** and **schneien**, it is oftentimes referring to the things that are raining or snowing, the raindrops or snowflakes, respectively. You can find **stattfinden** used more often than **regnan** and **schneien** in the third-person plural as it can refer to multiple things taking place.

For example:

- **Flocken schneien vom Himmel.** - *The snowflakes snow from the sky.*
- **Regenschauer regnen auf die Stadt nieder.** - *Rain showers rain down on the city.*
- **Die Spiele finden im Mai statt.** - *The games are taking place in May.*

However, in many instances you'll run into these verbs in the third-person singular:

- **Es schneit.** - *It is snowing.*
- **Es regnet** - *It is raining*
- **Es findet statt.** - *It is happening.*

::: {.callout-note}

A small note that there are prefixes that can be added to schneien (rein‑ / herein‑ / vorbei‑), which change the meaning from "to snow" to "to stop by (casually/unexpectedly)". As a result, these can exist in first- and second-person and you may seen them in a sentence like:

- **Ich schneie später rein.** - *I am stopping by later.*

:::

::: {.callout-tip title="**Exercise**"}


[Answer Key](03_Present_verb_conjugation_irregular-Answer_key.qmd)
:::


