---
title: "Shapes"
description: |
  In this lesson, we will practice shapes in German.
author:
  - Will Gammerdinger
date: 2026-05-30
categories: 
  - German
  - Shapes
keywords:
  - 2-dimensional
  - 3-dimensional
license: "CC BY-SA 4.0"
license-url: "https://creativecommons.org/licenses/by-sa/4.0/"
editor_options: 
  markdown: 
    wrap: 72
---

Approximate time: 30 minutes

# Learning Objectives

In this lesson, the learner will:

  - Identify 2-D and 3-D shapes

# 2-dimensional shapes

## Polygons

  Polygons in German are a little easier than in English, but it generally follows a similar pattern to English. As you increase the number of sides in English after a quadrilateral, you simply have a numerical prefix (penta-, hexa-, etc.) followed by *-gon*. The etymology of *-gon* in reference to shapes traces back to the Greek suffix -gōnia (-γωνο), which means angles. So something like *pentagon* can be broken down into "five angles"/"five corners".

  In German, like in English, they count the corners, but instead of waiting until pentagon to adopt the *numerical prefix + -corner* convention, they start it at triangle. The German word for corner is generally **die Ecke** <span class="pron" data-src="../audio/shapes/2d/Ecke.ogg">🔊</span>, but **das Eck** <span class="pron" data-src="../audio/shapes/2d/Eck.ogg">🔊</span> is another, less common way, to say corner. You may hear **das Eck** <span class="pron" data-src="../audio/shapes/2d/Eck.ogg">🔊</span> in Southern Germany, Austria and parts of Switzerland. It is also used to count the corners of polygons in German though. See the table below for the pattern of how polygons are named in German:

| English | German | English | German |
|:------:|:------:|:------:|:------:|
| triangle | **das Dreieck** <span class="pron" data-src="../audio/shapes/2d/Dreieck.ogg">🔊</span> | quadrilateral | **das Viereck** <span class="pron" data-src="../audio/shapes/2d/Viereck.ogg">🔊</span> |
| pentagon | **das Fünfeck** <span class="pron" data-src="../audio/shapes/2d/Fünfeck.ogg">🔊</span> | hexagon | **das Sechseck** <span class="pron" data-src="../audio/shapes/2d/Sechseck.ogg">🔊</span> |
| octagon | **das Achteck** <span class="pron" data-src="../audio/shapes/2d/Achteck.ogg">🔊</span> | decagon | **das Zehneck** <span class="pron" data-src="../audio/shapes/2d/Zehneck.ogg">🔊</span> |

  We can see that it is simply the number of corners in the polygon, followed by the **-eck** suffix. In fact, polygon translates directly to **das Vieleck** <span class="pron" data-src="../audio/shapes/2d/Vieleck.ogg">🔊</span> (**viel** <span class="pron" data-src="../audio/shapes/2d/viel.ogg">🔊</span> is the German word for "many"), so the connections between German and English for polygons are pretty strong.

## Special quadrilaterals

  While this pattern works for generally describing polygons, there are also some special quadrilaterals in German as well. In the same way that squares, rectangles and parallelograms are all special quadrilaterals in English, there are special names for different quadrilaterals, which can be found in the table below:

| English | German |
|:------:|:------:|
| square | **das Quadrat** <span class="pron" data-src="../audio/shapes/2d/Quadrat.ogg">🔊</span> |
| rectangle | **das Rechteck** <span class="pron" data-src="../audio/shapes/2d/Rechteck.ogg">🔊</span> |
| parallelogram | **das Parallelogramm** <span class="pron" data-src="../audio/shapes/2d/Parallelogramm.ogg">🔊</span> |
| rhombus / diamond | **die Raute** <span class="pron" data-src="../audio/shapes/2d/Raute.ogg">🔊</span> |
| trapezoid | **das Trapez** <span class="pron" data-src="../audio/shapes/2d/Trapez.ogg">🔊</span> |

## Curved Shapes

The table below outlines the curved shapes:

| English | German |
|:------:|:------:|
| circle | **der Kreis** <span class="pron" data-src="../audio/shapes/2d/Kreis.ogg">🔊</span> |
| semicircle | **der Halbkreis**\* <span class="pron" data-src="../audio/shapes/2d/Halbkreis.ogg">🔊</span> |
| oval | **das Oval** <span class="pron" data-src="../audio/shapes/2d/Oval.ogg">🔊</span> |

\* You can see that having our knowledge of fractions can help here since **der Halbkreis** <span class="pron" data-src="../audio/shapes/2d/Halbkreis.ogg">🔊</span> literally translates to "half circle".

:::{.callout-tip}
# Exercise 1

Use the app below to practice identifying 2-dimensional shapes in German.

<div style="width: 100%; max-width: 700px; margin: 0 auto;">
  <iframe
    id="shapes-2d"
    src="../apps/shapes/2d/shapes_to_names/index.html"
    style="width: 100%; border: 1px solid #ccc; border-radius: 6px;"
  ></iframe>
</div>

:::

# 3-dimensional shapes

## Prisms

  Let's start discussing three-dimensional shapes with the prisms, because they follow a simple pattern. In English, we take the name of the face for the prism and often add "-al prism" (pentagonal prism, hexagonal prism, etc.). Notably triangular and rectangular prisms don't fit that pattern in English. The good news is that in German the pattern is actually easier than English. In German, you take the name of the face of the prism and simply add **-ig Prisma**. So let's see how German constructs prism shapes in the table below:

| English | German |
|:------:|:------:|
| triangular prism | **das dreieckige** <span class="pron" data-src="../audio/shapes/3d/dreieckige.ogg">🔊</span> **Prisma** <span class="pron" data-src="../audio/shapes/3d/Prisma.ogg">🔊</span> |
| quadrilateral prism | **das viereckige** <span class="pron" data-src="../audio/shapes/3d/viereckige.ogg">🔊</span> **Prisma** <span class="pron" data-src="../audio/shapes/3d/Prisma.ogg">🔊</span> |
| pentagonal prism | **das fünfeckige** <span class="pron" data-src="../audio/shapes/3d/fünfeckige.ogg">🔊</span> **Prisma** <span class="pron" data-src="../audio/shapes/3d/Prisma.ogg">🔊</span> |
| hexagonal prism | **das sechseckige** <span class="pron" data-src="../audio/shapes/3d/sechseckige.ogg">🔊</span> **Prisma** <span class="pron" data-src="../audio/shapes/3d/Prisma.ogg">🔊</span> |

  You will notice that **-e** is appended to the end of **number + eckig**. This has to do with "three-cornered", "four-cornered", etc. are adjectives and this is the behavior for adjectives in this context. We are going to talk more about adjectives at a later point, so for now you can just remember to add **-e**.

:::{.callout-note}
The German word for "side" in relation to shapes is **die Seite** <span class="pron" data-src="../audio/shapes/3d/Seite.ogg">🔊</span> (notably also means page). Sometimes, instead of **-eckige**, you will see it referred to as "-sided", **-seitige**. So, triangular prisms might be referred to as **das dreiseitige** <span class="pron" data-src="../audio/shapes/3d/dreiseitige.ogg">🔊</span> **Prisma** <span class="pron" data-src="../audio/shapes/3d/Prisma.ogg">🔊</span>.
:::

## Special shapes

  Unfortunately like cube, cone and sphere in English, German has some unique names for some three-dimensional shapes that just need to be memorized. There is no pattern that you can rely on.

| English | German |
|:------:|:------:|
| cube | **der Würfel** <span class="pron" data-src="../audio/shapes/3d/Würfel.ogg">🔊</span> |
| rectangular prism | **der Quader**\* <span class="pron" data-src="../audio/shapes/3d/Quader.ogg">🔊</span> |
| triangular pyramid | **die dreieckige** <span class="pron" data-src="../audio/shapes/3d/dreieckige.ogg">🔊</span> **Pyramide** <span class="pron" data-src="../audio/shapes/3d/Pyramide.ogg">🔊</span>,<br>**der Tetraeder**\*\* <span class="pron" data-src="../audio/shapes/3d/Tetraeder.ogg">🔊</span> |
| square pyramid | **die viereckige** <span class="pron" data-src="../audio/shapes/3d/viereckige.ogg">🔊</span> **Pyramide** <span class="pron" data-src="../audio/shapes/3d/Pyramide.ogg">🔊</span> |
| cylinder | **der Zylinder** <span class="pron" data-src="../audio/shapes/3d/Zylinder.ogg">🔊</span> |
| cone | **der Kegel** <span class="pron" data-src="../audio/shapes/3d/Kegel.ogg">🔊</span> |
| sphere | **die Kugel** <span class="pron" data-src="../audio/shapes/3d/Kugel.ogg">🔊</span> |
| hemisphere | **die Halbkugel**\*\*\* <span class="pron" data-src="../audio/shapes/3d/Halbkugel.ogg">🔊</span> |

\* A rectangular prism (**der Quader** <span class="pron" data-src="../audio/shapes/3d/Quader.ogg">🔊</span>) is a special type of quadrilateral prism (**das viereckige Prisma**), because a prism of a trapezoid would be also be a type of quadrilateral prism, but not a rectangular prism. When describing a rectangular prism most Germans would use **der Quader** over **das viereckige Prisma** in the same way that English speakers would like use rectangular prism over quadrilateral prism. It sounds a bit geometry textbook-ish to say **das viereckige Prisma** just like quadrilateral prism sounds in English.

\*\* A triangular pyramid is also called a *tetrahedron* in English. In German geometry textbooks, you may see them refer to this shape in a similar way, **der Tetraeder** <span class="pron" data-src="../audio/shapes/3d/Tetraeder.ogg">🔊</span>. However, in German, both are common enough. 

\*\*\* Once again, like **Halbkreis** <span class="pron" data-src="../audio/shapes/2d/Halbkreis.ogg">🔊</span>, it is useful to know fractions since **Halbkugel** <span class="pron" data-src="../audio/shapes/3d/Halbkugel.ogg">🔊</span> literally translates to "half sphere".

:::{.callout-note}
Similarly to the prisms, you will sometimes see pyramids be referred to using the number of sides on the base, like **die dreiseitige Pyramide** and **die vierseitige Pyramide** for triangular pyramids and square pyramid, respectively, rather than the number of corners like provided in the table above.
:::

:::{.callout-tip}
# Exercise 2

Use the app below to practice identifying 3-dimensional shapes in German.

<div style="width: 100%; max-width: 700px; margin: 0 auto;">
  <iframe
    id="shapes-3d"
    src="../apps/shapes/3d/shapes_to_names/index.html"
    style="width: 100%; border: 1px solid #ccc; border-radius: 6px;"
  ></iframe>
</div>

:::

:::{.callout-tip}
# Exercise 3

Use the app below to practice identifying a mix of 2-dimensional and 3-dimensional shapes in German.

<div style="width: 100%; max-width: 700px; margin: 0 auto;">
  <iframe
    id="shapes-mixed"
    src="../apps/shapes/mixed/shapes_to_names/index.html"
    style="width: 100%; border: 1px solid #ccc; border-radius: 6px;"
  ></iframe>
</div>

:::

<style>
  /* Heights only for the apps on this page */

  #shapes-2d {
    height: 625px !important;
    max-height: 625px !important;
  }

  #shapes-3d {
    height: 625px !important;
    max-height: 625px !important;
  }
  
  #shapes-mixed {
    height: 625px !important;
    max-height: 625px !important;
  }
</style>
