---
title: "Time"
description: |
  In this lesson, we will practice telling time in German as well as discuss some common prepositions used with time.
author:
  - Will Gammerdinger
date: 2026-05-30
categories: 
  - German
  - Time
keywords:
  - Telling time
  - Uhr vs. Stunde
  - Time prepositions
license: "CC BY-SA 4.0"
license-url: "https://creativecommons.org/licenses/by-sa/4.0/"
editor_options: 
  markdown: 
    wrap: 72
---

Approximate time: 30 minutes

# Learning Objectives

In this lesson, the learner will:

  - Identify time
  - Use **um**, **ab**, **von** and **bis** in basic time expressions

# 12-hour and 24-hour clocks

In many English speaking countries, people tend to either use a 12-hour (AM and PM) or 24-hour system for telling time. But in German it is more of a mix and we will try to highlight the context of when each might be used in this lesson. When writing times as numbers, like 05:15, 13:30 and 17:35, they are almost always written in a 24‑hour format. However, how one might say those times or write them out in words could have some variety that we will explore in this lesson. First, you’ll learn how to write full hours, then add minutes, then learn the special shortcuts Germans use and finally how to use some common time prepositions.

# Wie spät ist es?

A common way to ask for the time in German is with the expression, **Wie spät ist es?** <span class="tts-de" data-text="Wie spät ist es?">🔊</span>, which would literally translate to "How late is it?". We will be using this in our exercises to ask you for the time, so it will be a good expression to get yourself acquainted with.

# Hours

Let's start by discussing how hours are described. In English, we sometimes describe time by saying the hour followed by "o'clock", which is a contraction for "of the clock". This principle carries over nicely to German, because they will say the hour followed by **Uhr** <span class="pron" data-src="../audio/numbers/time/Uhr.ogg">🔊</span>, which in other contexts can mean "clock" or "watch", but in this context is most similar to English's "o'clock". The table below lays out the hourly times in German:

::: {.vcenter-table}
| Time | German | Time | German |
|:---:|:------:|:---:|:------:|
| 12:00 AM | **zwölf Uhr** <span class="tts-de" data-text="zwölf Uhr">🔊</span><br>**die Mitternacht** <span class="pron" data-src="../audio/numbers/time/Mitternacht.ogg">🔊</span> | 12:00 PM | **zwölf Uhr** <span class="tts-de" data-text="zwölf Uhr">🔊</span><br>**der Mittag** <span class="pron" data-src="../audio/numbers/time/Mittag.ogg">🔊</span> |
| 1:00 AM | **ein Uhr** <span class="tts-de" data-text="ein Uhr">🔊</span> | 1:00 PM | **ein Uhr** <span class="tts-de" data-text="ein Uhr">🔊</span><br>**dreizehn Uhr** <span class="tts-de" data-text="dreizehn Uhr">🔊</span> |
| 2:00 AM | **zwei Uhr** <span class="tts-de" data-text="zwei Uhr">🔊</span>| 2:00 PM | **zwei Uhr** <span class="tts-de" data-text="zwei Uhr">🔊</span><br>**vierzehn Uhr** <span class="tts-de" data-text="vierzehn Uhr">🔊</span> |
| 3:00 AM | **drei Uhr** <span class="tts-de" data-text="drei Uhr">🔊</span>| 3:00 PM | **drei Uhr** <span class="tts-de" data-text="drei Uhr">🔊</span><br>**fünfzehn Uhr** <span class="tts-de" data-text="fünfzehn Uhr">🔊</span> |
| 4:00 AM | **vier Uhr** <span class="tts-de" data-text="vier Uhr">🔊</span>| 4:00 PM | **vier Uhr** <span class="tts-de" data-text="vier Uhr">🔊</span><br>**sechzehn Uhr** <span class="tts-de" data-text="sechzehn Uhr">🔊</span> |
| 5:00 AM | **fünf Uhr** <span class="tts-de" data-text="fünf Uhr">🔊</span>| 5:00 PM | **fünf Uhr** <span class="tts-de" data-text="fünf Uhr">🔊</span><br>**siebzehn Uhr** <span class="tts-de" data-text="siebzehn Uhr">🔊</span> |
| 6:00 AM | **sechs Uhr** <span class="tts-de" data-text="sechs Uhr">🔊</span>| 6:00 PM | **sechs Uhr** <span class="tts-de" data-text="sechs Uhr">🔊</span><br>**achtzehn Uhr** <span class="tts-de" data-text="achtzehn Uhr">🔊</span> |
| 7:00 AM | **sieben Uhr** <span class="tts-de" data-text="sieben Uhr">🔊</span>| 7:00 PM | **sieben Uhr** <span class="tts-de" data-text="sieben Uhr">🔊</span><br>**neunzehn Uhr** <span class="tts-de" data-text="neunzehn Uhr">🔊</span> |
| 8:00 AM | **acht Uhr** <span class="tts-de" data-text="acht Uhr">🔊</span>| 8:00 PM | **acht Uhr** <span class="tts-de" data-text="acht Uhr">🔊</span><br>**zwanzig Uhr** <span class="tts-de" data-text="zwanzig Uhr">🔊</span> |
| 9:00 AM | **neun Uhr** <span class="tts-de" data-text="neun Uhr">🔊</span>| 9:00 PM | **neun Uhr** <span class="tts-de" data-text="neun Uhr">🔊</span><br>**einundzwanzig Uhr** <span class="tts-de" data-text="einundzwanzig Uhr">🔊</span> |
| 10:00 AM | **zehn Uhr** <span class="tts-de" data-text="zehn Uhr">🔊</span>| 10:00 PM | **zehn Uhr** <span class="tts-de" data-text="zehn Uhr">🔊</span><br>**zweiundzwanzig Uhr** <span class="tts-de" data-text="zweiundzwanzig Uhr">🔊</span> |
| 11:00 AM | **elf Uhr** <span class="tts-de" data-text="elf Uhr">🔊</span>| 11:00 PM | **elf Uhr** <span class="tts-de" data-text="elf Uhr">🔊</span><br>**dreiundzwanzig Uhr** <span class="tts-de" data-text="dreiundzwanzig Uhr">🔊</span> |
:::

A few things will likely stand out to you from this table:

- Midnight generally uses **zwölf Uhr** <span class="tts-de" data-text="zwölf Uhr">🔊</span> or **die Mitternacht** <span class="pron" data-src="../audio/numbers/time/Mitternacht.ogg">🔊</span> over something like **null Uhr** <span class="tts-de" data-text="null Uhr">🔊</span> or **vierundzwanzig Uhr** <span class="tts-de" data-text="vierundzwanzig Uhr">🔊</span>, but in some contexts you may see 0 Uhr.
- PM times can be described both by their 12-hour time and their 24-hour time. Both are used often enough.
- Because PM times can sometimes use 12-hour times, you might think that leaves some ambiguity, but in reality you can usually piece it together from context. If you tell your friend that you will meet them for coffee at 3 o'clock in English, most people would assume PM over AM. The same idea exists in German as well. That being said, you can make it more explicit if it feels warranted. In the same way that you might tell your friend that you are meeting them at 7 o'clock "in the morning" or "at night" to remove that ambiguity. The table below gives loose guidelines on what phrase to append to the time to remove that ambiguity, such that 7 AM would be **sieben Uhr morgens** <span class="tts-de" data-text="sieben Uhr morgens">🔊</span>, while 7 PM would be **sieben Uhr abends** <span class="tts-de" data-text="sieben Uhr abends">🔊</span>:

| Time of Day | German | English |
|:---:|:------:|:---:|
| 5 AM - 10 AM | **morgens** <span class="pron" data-src="../audio/numbers/time/morgens.ogg">🔊</span> | morning |
| 9 AM - 12 PM | **vormittags** <span class="pron" data-src="../audio/numbers/time/vormittags.ogg">🔊</span> | late morning |
| 12 PM - 5 PM | **nachmittags** <span class="pron" data-src="../audio/numbers/time/nachmittags.ogg">🔊</span> | afternoon |
| 5 PM - 10 PM | **abends** <span class="pron" data-src="../audio/numbers/time/abends.ogg">🔊</span> | evening |
| 10 PM - 4 AM | **nachts** <span class="pron" data-src="../audio/numbers/time/nachts.ogg">🔊</span> | night |

You can notice in the table that we describe late morning with **vormittags** <span class="pron" data-src="../audio/numbers/time/vormittags.ogg">🔊</span> and afternoon with **nachmittags** <span class="pron" data-src="../audio/numbers/time/nachmittags.ogg">🔊</span>, while in the early table noon was translated as **der Mittag** <span class="pron" data-src="../audio/numbers/time/Mittag.ogg">🔊</span>. You may be able to guess, correctly, that **vor** <span class="pron" data-src="../audio/prepositions/vor.ogg">🔊</span> can mean "before" and **nach** <span class="pron" data-src="../audio/prepositions/nach.ogg">🔊</span> can mean "after". So **vormittags** <span class="pron" data-src="../audio/numbers/time/vormittags.ogg">🔊</span> literally translates to "before noon" and **nachmittags** <span class="pron" data-src="../audio/numbers/time/nachmittags.ogg">🔊</span> literally translates to "after noon", or "afternoon". The words **vor** <span class="pron" data-src="../audio/prepositions/vor.ogg">🔊</span> and **nach** <span class="pron" data-src="../audio/prepositions/nach.ogg">🔊</span> can have other uses as prepositions that we will explore in later lessons. 

:::{.callout-note}
# Don't confuse Uhr and Stunde!
It is really important to note that it can be tempting to think of **Uhr** <span class="pron" data-src="../audio/numbers/time/Uhr.ogg">🔊</span> as "hour", because it sort of sounds like a cognate for "hour" and you might think of it standing in the place for "hour" when talking about time. However, it isn't and I can assure you that it's only going to confuse you later. The word for "hour" is **die Stunde** <span class="pron" data-src="../audio/numbers/time/Stunde.ogg">🔊</span> and if you think about **Uhr** <span class="pron" data-src="../audio/numbers/time/Uhr.ogg">🔊</span> being "hour" rather than "o'clock", then you will almost certainly misuse **Uhr** <span class="pron" data-src="../audio/numbers/time/Uhr.ogg">🔊</span> when you mean to use **Stunde** <span class="pron" data-src="../audio/numbers/time/Stunde.ogg">🔊</span>. So think about **Uhr** <span class="pron" data-src="../audio/numbers/time/Uhr.ogg">🔊</span> being more like "o'clock", but also "clock" or "watch" as well.
:::

:::{.callout-tip}
# Exercise 1

Use the app below to practice telling time by the hour

<div style="width: 100%; max-width: 700px; margin: 0 auto;">
  <iframe
    id="app-time-hours"
    src="../apps/time/hours/"
    style="width: 100%; border: 1px solid #ccc; border-radius: 6px;"
  ></iframe>
</div>

:::

# Minutes

The most straightforward way of stating the time including minutes in German is to use *hour* + **Uhr** + *minutes*. When doing this, you can use 12-hour or 24-hour time. Below are a few examples of how various times may occur:

::: {.vcenter-table}
| Time | German |
|:---:|:---:|
| 5:20 AM | **fünf Uhr zwanzig** <span class="tts-de" data-text="fünf Uhr zwanzig">🔊</span><br>**fünf Uhr zwanzig morgens** <span class="tts-de" data-text="fünf Uhr zwanzig morgens">🔊</span> |
| 12:40 PM | **zwölf Uhr vierzig** <span class="tts-de" data-text="zwölf Uhr vierzig">🔊</span><br>**zwölf Uhr vierzig nachmittags** <span class="tts-de" data-text="zwölf Uhr vierzig nachmittags">🔊</span> |
| 7:10 PM | **sieben Uhr zehn** <span class="tts-de" data-text="sieben Uhr zehn">🔊</span><br>**sieben Uhr zehn abends** <span class="tts-de" data-text="sieben Uhr zehn abends">🔊</span><br>**neunzehn Uhr zehn** <span class="tts-de" data-text="neunzehn Uhr zehn">🔊</span> |
| 11:18 PM | **elf Uhr achtzehn** <span class="tts-de" data-text="elf Uhr achtzehn">🔊</span><br>**elf Uhr achtzehn nachts** <span class="tts-de" data-text="elf Uhr achtzehn nachts">🔊</span><br>**dreiundzwanzig Uhr achtzehn** <span class="tts-de" data-text="dreiundzwanzig Uhr achtzehn">🔊</span> |
:::

You can see that in the table, there are several ways to describe a given time and all are valid ways to do so.

:::{.callout-tip}
# Exercise 2

Use the app below to practice telling time to the closest five minute mark. Do not provide **morgens**, **vormittags**, etc. in this exercise.

<div style="width: 100%; max-width: 700px; margin: 0 auto;">
  <iframe
    id="app-time-minutes"
    src="../apps/time/minutes/"
    style="width: 100%; border: 1px solid #ccc; border-radius: 6px;"
  ></iframe>
</div>

:::

# Special cases

In English, we have special names for certain times. For example, the half-hour mark is sometimes colloquially called "half past" some hour. Or the :15 and :45 marks are sometimes called "quarter past" or "quarter of" some hour, respectively. These special cases exist in German.  We will discuss each in the subsections below:

:::{.callout-note}
# Special cases only use 12-hour time!
It is important to note that these "special cases" ONLY use the 12-hour time and are not used with 24-hour time. You can append **morgens** <span class="pron" data-src="../audio/numbers/time/morgens.ogg">🔊</span>, **vormittags** <span class="pron" data-src="../audio/numbers/time/vormittags.ogg">🔊</span>, **nachmittags** <span class="pron" data-src="../audio/numbers/time/nachmittags.ogg">🔊</span>, **abends** <span class="pron" data-src="../audio/numbers/time/abends.ogg">🔊</span> and **nachts** <span class="pron" data-src="../audio/numbers/time/nachts.ogg">🔊</span> in order to add specificity if you would like. In the examples in the following subsections, I will intentionally not be providing AM and PM to emphasize this point. You don’t have to use these to be understood, but you will hear them often from native speakers, so it’s important to recognize them.
:::

## Half-hour

The half-hour mark is likely the most difficult of these special cases because it doesn't behave the same way in German as it does English. A time like 5:30 would be called "half past five" but in German the nuance is that the "half past" turns into "half before" and so in German it is "half before six", or **halb sechs** <span class="tts-de" data-text="halb sechs">🔊</span>. Recall from our fractions that **halb** <span class="pron" data-src="../audio/numbers/fractions/Halb.ogg">🔊</span>, means 1/2. So 6:30 is halb sieben and 8:30 is halb neun and so on.

## Quarter-hour

The quarter-hour marks function exactly the same in German as they do in English and armed with our knowledge of **vor** <span class="pron" data-src="../audio/prepositions/vor.ogg">🔊</span> and **nach** <span class="pron" data-src="../audio/prepositions/nach.ogg">🔊</span> from earlier along with **Viertel** <span class="pron" data-src="../audio/numbers/fractions/Viertel.ogg">🔊</span> being a "quarter" or "1/4", we can describe these quarter hour marks. The time 5:45 can be described as **Viertel vor sechs** <span class="tts-de" data-text="Viertel vor sechs">🔊</span>, or "quarter before six", and 6:15 can be described as **Viertel nach sechs** <span class="tts-de" data-text="Viertel nach sechs">🔊</span>, or "quarter past six".

## Five or ten minutes prior to and after the hour

Just like the quarter-hour marks, we can use **vor** <span class="pron" data-src="../audio/prepositions/vor.ogg">🔊</span> and **nach** <span class="pron" data-src="../audio/prepositions/nach.ogg">🔊</span> along with **fünf** <span class="pron" data-src="../audio/numbers/0_9/fünf.ogg">🔊</span> and **zehn** <span class="pron" data-src="../audio/numbers/10_19/zehn.ogg">🔊</span> to describe five or ten minutes prior to and after the hour. For example, 5:55 could be **fünf vor sechs** <span class="tts-de" data-text="fünf vor sechs">🔊</span> and 6:05 could be **fünf nach sechs** <span class="tts-de" data-text="fünf nach sechs">🔊</span>, while 5:50 could be **zehn vor sechs** <span class="tts-de" data-text="zehn vor sechs">🔊</span> and 6:10 could be **zehn nach sechs** <span class="tts-de" data-text="zehn nach sechs">🔊</span>.

## Five or ten minutes prior to and after the half-hour

The same principles for describing five or ten minutes prior to and after the hour can also be applied to the half-hour mark. For example, 5:20 could be **zehn vor halb sechs** <span class="tts-de" data-text="zehn vor halb sechs">🔊</span>, 5:25 could be **fünf vor halb sechs** <span class="tts-de" data-text="fünf vor halb sechs">🔊</span>, 5:35 could be **fünf nach halb sechs** <span class="tts-de" data-text="fünf nach halb sechs">🔊</span> and 5:40 could be **zehn nach halb sechs** <span class="tts-de" data-text="zehn nach halb sechs">🔊</span>.

:::{.callout-tip}
# Exercise 3

Use the app below to practice telling time to the closest five minute mark. Do not provide **morgens**, **vormittags**, etc. in this exercise.

<div style="width: 100%; max-width: 700px; margin: 0 auto;">
  <iframe
    id="app-time-full"
    src="../apps/time/full/"
    style="width: 100%; border: 1px solid #ccc; border-radius: 6px;"
  ></iframe>
</div>

:::

# Um, Von, Ab and Bis 

There are four prepositions that are quite helpful with time: **um** <span class="pron" data-src="../audio/prepositions/um.ogg">🔊</span>, **ab** <span class="pron" data-src="../audio/prepositions/ab.ogg">🔊</span>, **von** <span class="pron" data-src="../audio/prepositions/von.ogg">🔊</span> and **bis** <span class="pron" data-src="../audio/prepositions/bis.ogg">🔊</span>. All four of these prepositions have other non-time uses contexts that we will discuss when we discuss prepositions. But in the context of time, **um** <span class="pron" data-src="../audio/prepositions/um.ogg">🔊</span> means "at", **ab** <span class="pron" data-src="../audio/prepositions/ab.ogg">🔊</span> means 'from' in the sense of 'starting at and continuing from then on', **von** <span class="pron" data-src="../audio/prepositions/von.ogg">🔊</span> means 'from' and is almost always paired with **bis** <span class="pron" data-src="../audio/prepositions/bis.ogg">🔊</span> to define a time range and **bis** <span class="pron" data-src="../audio/prepositions/bis.ogg">🔊</span> means "until". Some examples of using these prepositions in sentences could look like:

- *Wir treffen um sechs Uhr.* <span class="tts-de" data-text="Wir treffen um sechs Uhr.">🔊</span> "We are meeting at six o'clock."
- *Ich studiere ab neun Uhr.* <span class="tts-de" data-text="Ich studiere ab neun Uhr.">🔊</span> "I study from nine o'clock on."
- *Ich arbeite bis vier Uhr.* <span class="tts-de" data-text="Ich arbeite bis vier Uhr.">🔊</span> "I am working until four o'clock."
- *Die Party ist von fünf Uhr bis acht Uhr.* <span class="tts-de" data-text="Die Party ist von fünf Uhr bis acht Uhr.">🔊</span> "The party is from five o'clock until eight o'clock."

:::{.callout-note}
# Using Uhr once with von..bis...
In the last example sentence, **Die Party ist von fünf Uhr bis acht Uhr** <span class="tts-de" data-text="Die Party ist von fünf Uhr bis acht Uhr.">🔊</span>, you can see that we used **Uhr** <span class="pron" data-src="../audio/numbers/time/Uhr.ogg">🔊</span> twice in this sentence. You can also say **Die Party ist von fünf bis acht Uhr** <span class="tts-de" data-text="Die Party ist von fünf bis acht Uhr.">🔊</span> and a literal translation would be "The party is from five until eight o'clock." Both ways of structuring the sentence are fine and used commonly enough.
:::

<style>
  /* Heights only for the apps on this page */

  #app-time-hours {
    height: 625px !important;
    max-height: 625px !important;
  }
  
  #app-time-minutes {
    height: 625px !important;
    max-height: 625px !important;
  }
  
  #app-time-full {
    height: 625px !important;
    max-height: 625px !important;
  }

</style>
